baseURL: "http://example.org/"
languageCode: "en-us"
title: "Erik Gomez"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Erik Gomez"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Erik Gomez" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Erik."
    subtitle: "I am a fullstack software engineer."
    content: "As a passionate software engineer, I enjoy learning new tools and frameworks to help me build scalable and robust systems.

    \n\nWhat I'm currently reading: Designing Data-Intensive Applications"
    # image: /images/about_me.JPG
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: /resume/Erik_Gomez_Resume.pdf
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/erikchomez
        - icon: fab fa-linkedin-in
          url: "https://example.com"
        - icon: fa fa-envelope
          url: "unierikgomez@gmail.com"
        

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/about_me.JPG
    roundImage: true
    content: |-
      I am a software developer with a passion for developing scalable and robust systems. I have a background in computer science with a focus in machine learning, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [VMware](https://vmware.com) in Palo Alto, CA. 

      I recently finished working on a project to optimize our internal resource lock manager, and will begin working on a new initiative to add workflows for adding, applying, and managing custom ISOs.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "Maven"
        - "Python"
        - "Spring"
        - "Typescript"
        - "PostgreSQL"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer II"
        company: "VMware"
        companyUrl: "https://vmware.com"
        date: "Feb 2022 - present"
        # TODO: add resume bullet points here
        content: |-
          - Maintained and supported VCF, a distributed Java application with over 1 million lines of code, using Maven, PostgreSQL, and Spring
          - Designed and implemented Jenkins CI pipelines to automate integration testing. Achieved an 80% increase in productivity and efficiency by streamlining the integration testing process through automation.
          - Leveraged JProfiler and JMC to identify high memory and CPU usage workflows in scale environments. Implemented a redesigned frugal locking algorithm resulting in up to a 95% reduction in overhead.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.S. Computer Science"
        school:
          name: "University of California, Irvine"
          url: "https://uci.edu/"
        date: "2018 - 2021"
        content: |-
          Area of focus:
            - AI
            - Computer Vision
            - Machine Learning
            - Optimization Algorithms
        # featuredLink:
        #   enable: true
        #   name: "Reinforcement learning project to teach an agent in Minecraft to optimize wheat harvesting"
        #   url: "https://erikchomez.github.io/TheRealFarmerJohn/index.html"


  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: TheRealFarmerJohn
        content: A reinforcement learning project using Project Malmo to teach an agent to optimize for wheat harvesting.
        image: /images/farmer_john.png
        featured:
          name: Project Writeup
          link: https://erikchomez.github.io/TheRealFarmerJohn/index.html
        badges:
          - "Project Malmo"
          - "AI"
          - "Reinforcement Learning"
        links:
          - icon: fab fa-github
            url: https://github.com/erikchomez/TheRealFarmerJohn

      - title: 3D Object Reconstruction
        content: A pipeline for producing high-quality 3D reconstruction of an object from a collection of structured light scans.
        image: /images/3d_recon.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "OpenCV"
          - "Computer Vision"
        links:
          - icon: fab fa-github
            url: https://github.com/erikchomez/3D-Object-Reconstruction

      - title: Face Morphing and Swapping
        content: A project to develop a function to warp from one face to another using piecewise affine warping. Which will be used to perform morphing and face swapping.
        image: /images/face_morph.gif
        badges:
          - "Python"
          - "Art&Code"
        links:
          - icon: fab fa-github
            url: https://github.com/erikchomez/face-morphing-and-swapping

      - title: Pointillism Painting
        content: A simple Python program to convert images to pointillism style.
        image: /images/tokyo_edit.gif
        badges:
          - "Python"
          - "Art&Code"
        links:
          - icon: fab fa-github
            url: https://github.com/erikchomez/Pointillism


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: unierikgomez@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/erikchomez
      linkedin: https://www.linkedin.com/in/erik-gomez/
      instagram: https://www.instagram.com/erikchomez/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
